# Generated by Django 5.2.7 on 2025-10-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_partners',
            field=models.BooleanField(default=False, help_text='Whether this project involves partner organizations'),
        ),
        migrations.AddField(
            model_name='project',
            name='partner_organizations',
            field=models.JSONField(default=list, help_text='List of partner organizations involved in this project'),
        ),
        migrations.AddField(
            model_name='project',
            name='targeted_commodities',
            field=models.JSONField(default=list, help_text='List of commodities this project focuses on'),
        ),
        migrations.AddField(
            model_name='project',
            name='targeted_countries',
            field=models.JSONField(default=list, help_text='List of countries/regions this project covers'),
        ),
        migrations.AddField(
            model_name='project',
            name='targeted_respondents',
            field=models.JSONField(default=list, help_text='List of respondent types targeted for this project'),
        ),
    ]
