# Generated by Django 5.2.7 on 2025-10-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0002_project_has_partners_project_partner_organizations_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="owner_database_endpoint",
            field=models.URLField(
                blank=True,
                help_text="AWS RDS or database endpoint URL where owner's responses should be stored",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="partner_organizations",
            field=models.JSONField(
                default=list,
                help_text="List of partner organizations with their database endpoints. Format: [{'name': 'Partner ABC', 'database_endpoint': 'https://...', 'api_key': '...'}]",
            ),
        ),
    ]
