# Generated by Django 5.2.7 on 2025-10-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_owner_database_endpoint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmember",
            name="partner_organization",
            field=models.CharField(
                blank=True,
                help_text="Name of partner organization this member represents (must match project.partner_organizations)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pendinginvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "Member"),
                    ("analyst", "Analyst"),
                    ("collaborator", "Collaborator"),
                    ("partner", "Partner Organization"),
                    ("viewer", "Viewer"),
                ],
                default="member",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "Member"),
                    ("analyst", "Analyst"),
                    ("collaborator", "Collaborator"),
                    ("partner", "Partner Organization"),
                    ("viewer", "Viewer"),
                ],
                default="member",
                max_length=20,
            ),
        ),
    ]
