# Generated by Django 5.2.7 on 2025-10-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_add_partner_organization_to_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="owner_database_endpoint",
            field=models.URLField(
                blank=True,
                help_text="Optional: AWS RDS or database endpoint URL where owner's responses should be stored",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="partner_organizations",
            field=models.JSONField(
                default=list,
                help_text="List of partner organizations. Format: [{'name': 'Partner ABC', 'contact_email': 'email@partner.org', 'database_endpoint': 'https://...' (optional), 'api_key': '...' (optional)}]",
            ),
        ),
    ]
