# Generated by Django 5.2.4 on 2025-12-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_project_owner_database_endpoint_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectmember",
            name="permissions",
        ),
        migrations.AlterField(
            model_name="pendinginvitation",
            name="role",
            field=models.CharField(
                choices=[("member", "Member"), ("partner", "Partner Organization")],
                default="member",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="role",
            field=models.CharField(
                choices=[("member", "Member"), ("partner", "Partner Organization")],
                default="member",
                max_length=20,
            ),
        ),
    ]
