# Generated by Django 5.2.8 on 2026-02-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_remove_projectmember_permissions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmember",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("active", "Active")],
                default="active",
                max_length=20,
            ),
        ),
    ]
