# Generated by Django 5.2.8 on 2026-06-12 01:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectmember_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('respondent_type', models.CharField(max_length=50)),
                ('commodity', models.CharField(blank=True, default='', max_length=50)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('target_count', models.PositiveIntegerField(help_text='Target number of completed respondents for this bundle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_targets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_targets', to='projects.project')),
            ],
            options={
                'ordering': ['assigned_to', 'respondent_type', 'commodity', 'country'],
                'unique_together': {('project', 'respondent_type', 'commodity', 'country', 'assigned_to')},
            },
        ),
    ]
