# Generated by Django 5.2.7 on 2025-10-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("responses", "0002_add_question_bank_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="database_routing_status",
            field=models.JSONField(
                default=dict,
                help_text="Tracks submission status for each database endpoint. Format: {'owner': {...}, 'Partner A': {...}}",
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="last_routing_attempt",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of last routing attempt", null=True
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="routing_attempts",
            field=models.IntegerField(
                default=0, help_text="Number of routing attempts made"
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="routing_complete",
            field=models.BooleanField(
                default=False,
                help_text="True if response has been successfully sent to all target databases",
            ),
        ),
    ]
