# Generated by Django 5.2.7 on 2025-10-16 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0007_remove_question_unique_question_per_project"),
        ("projects", "0005_alter_project_owner_database_endpoint_and_more"),
        ("responses", "0003_add_multi_database_routing_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="is_owner_question",
            field=models.BooleanField(
                default=True,
                help_text="Whether this response is for a project owner question",
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="question_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("production", "Production"),
                    ("processing", "Processing"),
                    ("distribution", "Distribution"),
                    ("consumption", "Consumption"),
                    ("waste_management", "Waste Management"),
                    ("input_supply", "Input Supply"),
                    ("market_access", "Market Access"),
                    ("quality_standards", "Quality Standards"),
                    ("certification", "Certification"),
                    ("sustainability", "Sustainability"),
                    ("climate_impact", "Climate Impact"),
                    ("social_impact", "Social Impact"),
                    ("economic_impact", "Economic Impact"),
                    ("governance", "Governance"),
                    ("policy", "Policy"),
                    ("technology", "Technology"),
                    ("logistics", "Logistics"),
                    ("finance", "Finance"),
                    ("nutrition", "Nutrition"),
                    ("food_safety", "Food Safety"),
                ],
                help_text="Category from QuestionBank for value chain analysis",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="question_data_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("internal", "Internal Research Team"),
                    ("partner_university", "Partner University"),
                    ("partner_ngo", "Partner NGO"),
                    ("partner_government", "Partner Government Agency"),
                    ("partner_private", "Partner Private Organization"),
                    ("partner_international", "Partner International Organization"),
                    ("consultant", "External Consultant"),
                    ("collaborative", "Collaborative Development"),
                ],
                default="internal",
                help_text="Data source/research partner from QuestionBank",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="question_sources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of sources (owner and/or partner names) for this question",
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="research_partner_name",
            field=models.CharField(
                blank=True,
                help_text="Name of research partner from QuestionBank",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="work_package",
            field=models.CharField(
                blank=True,
                help_text="Work package identifier from QuestionBank",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="respondent",
            name="commodity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cocoa", "Cocoa"),
                    ("maize", "Maize"),
                    ("palm_oil", "Palm Oil"),
                    ("groundnut", "Groundnut"),
                    ("honey", "Honey"),
                ],
                help_text="Commodity from QuestionBank.COMMODITY_CHOICES",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="respondent",
            name="respondent_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("input_suppliers", "Input Suppliers"),
                    ("farmers", "Farmers"),
                    ("aggregators_lbcs", "Aggregators/LBCs"),
                    ("processors", "Processors"),
                    ("processors_eu", "Processors EU"),
                    ("retailers_food_vendors", "Retailers/Food Vendors"),
                    ("retailers_food_vendors_eu", "Retailers/Food Vendors EU"),
                    ("local_consumers", "Local Consumers"),
                    ("consumers_eu_prolific", "Consumers EU (Prolific)"),
                    ("client_business_eu_prolific", "Client/Business EU (Prolific)"),
                    ("government", "Government"),
                    ("ngos", "NGOs"),
                    ("certification_schemes", "Certification Schemes"),
                    ("coop", "COOP"),
                    ("chief", "Chief"),
                ],
                help_text="Type of respondent from QuestionBank.RESPONDENT_CHOICES",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="question_bank_context",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Full context from question bank including: respondent_type, commodity, country, category, data_source, etc.",
            ),
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(
                fields=["question_category"], name="responses_r_questio_bfda74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(
                fields=["question_data_source"], name="responses_r_questio_41fccb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(
                fields=["work_package"], name="responses_r_work_pa_86d150_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(
                fields=["is_owner_question"], name="responses_r_is_owne_cf47d3_idx"
            ),
        ),
    ]
