# Generated by Django 5.2.8 on 2025-12-16 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_alter_question_options_and_more'),
        ('responses', '0005_responselink'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='completion_status',
            field=models.CharField(choices=[('draft', 'Draft - In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='draft', help_text='Status of response collection for this respondent', max_length=20),
        ),
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='forms.question'),
        ),
    ]
