# Generated by Django 5.2.8 on 2026-02-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("responses", "0006_respondent_completion_status_alter_response_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="respondent",
            name="draft_name",
            field=models.CharField(
                blank=True,
                help_text="User-assigned name for easy draft identification",
                max_length=255,
                null=True,
            ),
        ),
    ]
