# Generated by Django 5.2.7 on 2025-10-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_question_assigned_commodity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_owner_question',
            field=models.BooleanField(default=True, help_text="True if this is the project owner's question, False if it's a partner's question"),
        ),
        migrations.AddField(
            model_name='question',
            name='partner_data_storage',
            field=models.CharField(blank=True, help_text="Partner's data storage endpoint/location for responses", max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='partner_organization',
            field=models.JSONField(blank=True, help_text='Partner organization information if this is a partner question', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='targeted_respondents',
            field=models.JSONField(default=list, help_text='List of respondent types this question targets'),
        ),
    ]
