# Generated by Django 5.2.7 on 2025-10-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0003_question_is_owner_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_sources",
            field=models.JSONField(
                default=list,
                help_text="List of sources this question belongs to. Can include 'owner' and/or partner names from project.partner_organizations",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="is_owner_question",
            field=models.BooleanField(
                default=True,
                help_text="True if this question belongs to the project owner",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="partner_data_storage",
            field=models.CharField(
                blank=True,
                help_text="DEPRECATED: Use question_sources instead. Partner's data storage endpoint/location for responses",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="partner_organization",
            field=models.JSONField(
                blank=True,
                help_text="DEPRECATED: Use question_sources instead. Partner organization information if this is a partner question",
                null=True,
            ),
        ),
    ]
