# Generated by Django 5.2.7 on 2025-10-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_question_question_sources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='is_owner_question',
            field=models.BooleanField(default=False, help_text='Whether this question is created by the project owner'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='question_sources',
            field=models.JSONField(blank=True, default=list, help_text='List of sources (owner and/or partner names) for this question'),
        ),
    ]
