# Generated by Django 5.2.7 on 2025-10-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0006_add_unique_constraint_question"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="question",
            name="unique_question_per_project",
        ),
    ]
