# Generated by Django 5.2.7 on 2025-10-16 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0007_remove_question_unique_question_per_project"),
        ("projects", "0005_alter_project_owner_database_endpoint_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="questionbank",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="If True, this QuestionBank item is accessible to all users",
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner of this QuestionBank item",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_question_banks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(fields=["owner"], name="forms_quest_owner_i_2f146b_idx"),
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(
                fields=["is_public"], name="forms_quest_is_publ_e8db1a_idx"
            ),
        ),
    ]
