# Generated by Django 5.2.7 on 2025-10-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0008_questionbank_is_public_questionbank_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionbank",
            name="question_category",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("production", "Production"),
                    ("processing", "Processing"),
                    ("distribution", "Distribution"),
                    ("consumption", "Consumption"),
                    ("waste_management", "Waste Management"),
                    ("input_supply", "Input Supply"),
                    ("market_access", "Market Access"),
                    ("quality_standards", "Quality Standards"),
                    ("certification", "Certification"),
                    ("sustainability", "Sustainability"),
                    ("climate_impact", "Climate Impact"),
                    ("social_impact", "Social Impact"),
                    ("economic_impact", "Economic Impact"),
                    ("governance", "Governance"),
                    ("policy", "Policy"),
                    ("technology", "Technology"),
                    ("logistics", "Logistics"),
                    ("finance", "Finance"),
                    ("nutrition", "Nutrition"),
                    ("food_safety", "Food Safety"),
                ],
                help_text="Category based on food system value chain",
                max_length=30,
            ),
        ),
    ]
