# Generated by Django 5.2.4 on 2025-12-06 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0010_add_conditional_logic"),
        ("projects", "0006_remove_projectmember_permissions_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="questionbank",
            name="forms_quest_questio_82043e_idx",
        ),
        migrations.RemoveIndex(
            model_name="questionbank",
            name="forms_quest_data_so_a86934_idx",
        ),
        migrations.RemoveIndex(
            model_name="questionbank",
            name="forms_quest_is_acti_e58bed_idx",
        ),
        migrations.RemoveIndex(
            model_name="questionbank",
            name="forms_quest_priorit_9dff28_idx",
        ),
        migrations.RemoveIndex(
            model_name="questionbank",
            name="forms_quest_owner_i_2f146b_idx",
        ),
        migrations.RemoveIndex(
            model_name="questionbank",
            name="forms_quest_is_publ_e8db1a_idx",
        ),
        migrations.RemoveField(
            model_name="questionbank",
            name="base_project",
        ),
        migrations.RemoveField(
            model_name="questionbank",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="questionbank",
            name="owner",
        ),
        migrations.AddField(
            model_name="questionbank",
            name="created_by_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this QuestionBank item",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_question_banks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Project this question bank item belongs to - question banks are project-specific",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_bank_items",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="conditional_logic",
            field=models.JSONField(
                blank=True,
                help_text='\n        Conditional logic for follow-up questions. Format:\n        {\n            "enabled": true,\n            "parent_question_id": "uuid-of-parent-question",\n            "show_if": {\n                "operator": "equals|contains|greater_than|less_than|in|not_in",\n                "value": "expected_value_or_list"\n            }\n        }\n        ',
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(
                fields=["project", "question_category"],
                name="forms_quest_project_ef620b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(
                fields=["project", "data_source"], name="forms_quest_project_82c4c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(
                fields=["project", "is_active"], name="forms_quest_project_54283b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(
                fields=["project", "priority_score"],
                name="forms_quest_project_77575a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(
                fields=["created_by_user"], name="forms_quest_created_57a194_idx"
            ),
        ),
    ]
