# Generated by Django 5.2.4 on 2025-12-06 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0012_populate_questionbank_project_and_user"),
        ("projects", "0006_remove_projectmember_permissions_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionbank",
            name="created_by_user",
            field=models.ForeignKey(
                help_text="User who created this QuestionBank item",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_question_banks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="project",
            field=models.ForeignKey(
                help_text="Project this question bank item belongs to - question banks are project-specific",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_bank_items",
                to="projects.project",
            ),
        ),
    ]
