# Generated by Django 5.1.6 on 2025-12-06 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_alter_questionbank_created_by_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_by_user',
            field=models.ForeignKey(blank=True, help_text='User who created/generated this question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='data_source',
            field=models.CharField(blank=True, choices=[('internal', 'Internal Research Team'), ('partner_university', 'Partner University'), ('partner_ngo', 'Partner NGO'), ('partner_government', 'Partner Government Agency'), ('partner_private', 'Partner Private Organization'), ('partner_international', 'Partner International Organization'), ('consultant', 'External Consultant'), ('collaborative', 'Collaborative Development')], default='internal', help_text='Source/partner who created this question', max_length=30),
        ),
        migrations.AddField(
            model_name='question',
            name='question_category',
            field=models.CharField(blank=True, help_text='Category/type of question for organization', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='research_partner_contact',
            field=models.EmailField(blank=True, help_text='Contact email for the research partner', max_length=254),
        ),
        migrations.AddField(
            model_name='question',
            name='research_partner_name',
            field=models.CharField(blank=True, help_text='Name of the specific research partner', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='work_package',
            field=models.CharField(blank=True, help_text='Work package identifier for this question', max_length=100),
        ),
    ]
