# Generated by Django 5.1.6 on 2025-12-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_question_created_by_user_question_data_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='data_source',
            field=models.CharField(blank=True, choices=[('internal', 'Internal Research Team'), ('partner_university', 'Partner University'), ('partner_ngo', 'Partner NGO'), ('partner_government', 'Partner Government Agency'), ('partner_private', 'Partner Private Organization'), ('partner_international', 'Partner International Organization'), ('consultant', 'External Consultant'), ('collaborative', 'Collaborative Development')], default='internal', help_text='Source/partner who created this question (default: internal)', max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_category',
            field=models.CharField(blank=True, default='general', help_text='Category/type of question for organization (auto-set from respondents if not provided)', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='research_partner_contact',
            field=models.EmailField(blank=True, default='', help_text='Contact email for the research partner (optional, not required)', max_length=254),
        ),
        migrations.AlterField(
            model_name='question',
            name='research_partner_name',
            field=models.CharField(blank=True, default='', help_text='Name of the specific research partner (optional, not required)', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='work_package',
            field=models.CharField(blank=True, default='', help_text='Work package identifier for this question (optional, not required)', max_length=100),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='data_source',
            field=models.CharField(choices=[('internal', 'Internal Research Team'), ('partner_university', 'Partner University'), ('partner_ngo', 'Partner NGO'), ('partner_government', 'Partner Government Agency'), ('partner_private', 'Partner Private Organization'), ('partner_international', 'Partner International Organization'), ('consultant', 'External Consultant'), ('collaborative', 'Collaborative Development')], default='internal', help_text='Source/partner who created this question (default: internal)', max_length=30),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='is_owner_question',
            field=models.BooleanField(default=True, help_text='Whether this question is created by the project owner (default: True)'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='priority_score',
            field=models.IntegerField(default=5, help_text='Priority for question selection (1-10, higher = more important, default: 5)'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='question_sources',
            field=models.JSONField(blank=True, default=list, help_text="List of sources (owner and/or partner names) for this question (default: ['owner'])"),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='research_partner_contact',
            field=models.EmailField(blank=True, default='', help_text='Contact email for the research partner (optional, not required for import)', max_length=254),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='research_partner_name',
            field=models.CharField(blank=True, default='', help_text='Name of the specific research partner (optional, not required for import)', max_length=200),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='work_package',
            field=models.CharField(blank=True, default='', help_text='Work package identifier for this question (optional, not required for import)', max_length=100),
        ),
    ]
