# Generated by Django 5.1.6 on 2025-12-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_update_fields_with_sensible_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='section_header',
            field=models.CharField(blank=True, default='', help_text='Section/group title - questions with the same section_header are grouped together', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='section_preamble',
            field=models.TextField(blank=True, default='', help_text='Introductory text displayed before the first question in this section'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='section_header',
            field=models.CharField(blank=True, default='', help_text='Section/group title - questions with the same section_header are grouped together', max_length=200),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='section_preamble',
            field=models.TextField(blank=True, default='', help_text='Introductory text displayed before the first question in this section'),
        ),
    ]
