# Generated by Django 5.2.8 on 2025-12-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_question_section_header_question_section_preamble_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_category', 'order_index', 'created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_category',
            field=models.CharField(blank=True, default='general', help_text='Custom category/label for organizing questions', max_length=100),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='question_category',
            field=models.CharField(blank=True, default='general', help_text="Custom category/label for organizing questions (e.g., 'Production', 'Market Access', etc.)", max_length=100),
        ),
    ]
